---
- name: Install packages
  action: apt pkg={{item}} state=latest update-cache=yes
  with_items:
  - pkg-config
  - build-essential
  - git-core
  - vim
  - curl
  - wget
  - python-pip
  - python-dev
  - libpq-dev
  - tree

- name: install virtualenv
  pip: name=virtualenv